import jsPDF from "jspdf";

export async function generateApplicationPdf(data: {
  applicantName: string;
  applicantEmail: string;
  applicantPhone?: string;
  propertyName: string;
  unitName: string;
  propertyAddress?: string;
  sections: {
    title: string;
    fields: { label: string; value: string; type: string }[];
  }[];
  signatureImage: string;
  signatureTypedName: string;
  signedAt: Date;
  ipAddress: string;
  userAgent: string;
  submittedAt: Date;
  applicationId: string;
}): Promise<Buffer> {
  const doc = new jsPDF();
  let y = 20;

  // ── Header ──
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(108, 92, 231);
  doc.text("DoorStax", 14, y);
  y += 8;

  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.text("Rental Application", 14, y);
  y += 4;

  doc.setDrawColor(108, 92, 231);
  doc.setLineWidth(0.5);
  doc.line(14, y, 196, y);
  y += 8;

  // ── Metadata ──
  doc.setFontSize(10);
  const meta: [string, string][] = [
    ["Applicant", data.applicantName],
    ["Email", data.applicantEmail],
  ];
  if (data.applicantPhone) meta.push(["Phone", data.applicantPhone]);
  meta.push(["Property", `${data.propertyName} \u2014 ${data.unitName}`]);
  if (data.propertyAddress) meta.push(["Address", data.propertyAddress]);
  meta.push([
    "Submitted",
    data.submittedAt.toLocaleString("en-US", {
      dateStyle: "full",
      timeStyle: "long",
    }),
  ]);
  meta.push(["Application ID", data.applicationId]);

  for (const [label, value] of meta) {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(80, 80, 80);
    doc.text(`${label}:`, 14, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    doc.text(value, 60, y);
    y += 6;
  }
  y += 6;

  // ── Sections ──
  for (const section of data.sections) {
    if (y > 255) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(108, 92, 231);
    doc.text(section.title, 14, y);
    y += 2;
    doc.setDrawColor(108, 92, 231);
    doc.setLineWidth(0.3);
    doc.line(14, y, 196, y);
    y += 6;

    doc.setFontSize(10);
    for (const field of section.fields) {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }

      doc.setFont("helvetica", "bold");
      doc.setTextColor(80, 80, 80);
      doc.text(field.label, 14, y);

      doc.setFont("helvetica", "normal");
      doc.setTextColor(40, 40, 40);
      const value = field.value || "\u2014";

      if (value.length > 80 || field.type === "TEXTAREA") {
        y += 5;
        const lines = doc.splitTextToSize(value, 170);
        doc.text(lines, 14, y);
        y += lines.length * 5 + 3;
      } else {
        doc.text(value, 80, y);
        y += 6;
      }
    }
    y += 4;
  }

  // ── Signature ──
  if (y > 215) {
    doc.addPage();
    y = 20;
  }

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(108, 92, 231);
  doc.text("Applicant Signature", 14, y);
  y += 2;
  doc.setDrawColor(108, 92, 231);
  doc.setLineWidth(0.3);
  doc.line(14, y, 196, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(80, 80, 80);
  doc.text("Signed by:", 14, y);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(40, 40, 40);
  doc.text(data.signatureTypedName, 50, y);
  y += 8;

  try {
    if (data.signatureImage?.startsWith("data:image")) {
      doc.addImage(data.signatureImage, "PNG", 14, y, 80, 30);
      y += 34;
    }
  } catch {
    doc.text("[Signature on file]", 14, y);
    y += 8;
  }

  doc.setDrawColor(150, 150, 150);
  doc.setLineWidth(0.3);
  doc.line(14, y, 100, y);
  y += 5;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Applicant Signature", 14, y);
  y += 4;
  doc.text(
    `Date: ${data.signedAt.toLocaleString("en-US", { dateStyle: "long", timeStyle: "long" })}`,
    14,
    y
  );
  y += 10;

  // ── Verification metadata ──
  doc.setFillColor(248, 248, 248);
  doc.setDrawColor(220, 220, 220);
  doc.roundedRect(14, y, 182, 26, 2, 2, "FD");
  y += 5;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Digital Verification", 18, y);
  y += 4;
  doc.setFontSize(7);
  doc.text(`Signed at: ${data.signedAt.toISOString()}`, 18, y);
  y += 3.5;
  doc.text(`IP Address: ${data.ipAddress}`, 18, y);
  y += 3.5;
  doc.text(
    `User Agent: ${(data.userAgent || "Unknown").substring(0, 120)}`,
    18,
    y
  );
  y += 3.5;
  doc.text(
    "This is a digitally signed document generated by DoorStax.",
    18,
    y
  );

  // ── Footer on every page ──
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(180, 180, 180);
    doc.text(
      `Generated by DoorStax \u00b7 Application ID: ${data.applicationId} \u00b7 Page ${i} of ${totalPages}`,
      105,
      290,
      { align: "center" }
    );
  }

  return Buffer.from(doc.output("arraybuffer"));
}
