/**
 * Platform-specific column mapping presets for tenant data migration.
 * Each preset maps the source platform's export column names to DoorStax field names.
 */

export interface PlatformPreset {
  id: string;
  name: string;
  description: string;
  instructions: string;
  columnAliases: Record<string, string>;
  supportedFields: string[];
}

export const DOORSTAX_FIELDS = [
  { key: "name", label: "Tenant Name", required: true },
  { key: "email", label: "Email", required: true },
  { key: "phone", label: "Phone", required: false },
  { key: "propertyName", label: "Property Name", required: true },
  { key: "address", label: "Property Address", required: false },
  { key: "city", label: "City", required: false },
  { key: "state", label: "State", required: false },
  { key: "zip", label: "ZIP Code", required: false },
  { key: "unitNumber", label: "Unit Number", required: true },
  { key: "bedrooms", label: "Bedrooms", required: false },
  { key: "bathrooms", label: "Bathrooms", required: false },
  { key: "sqft", label: "Sq Ft", required: false },
  { key: "rentAmount", label: "Rent Amount", required: true },
  { key: "leaseStart", label: "Lease Start", required: false },
  { key: "leaseEnd", label: "Lease End", required: false },
] as const;

export const MIGRATION_PRESETS: PlatformPreset[] = [
  {
    id: "buildium",
    name: "Buildium",
    description: "Import from Buildium tenant CSV export",
    instructions:
      "In Buildium, go to Residents → All Tenants → Export. Download the CSV file and upload it here.",
    columnAliases: {
      "tenant name": "name",
      "tenant": "name",
      "first name": "name",
      "tenant email": "email",
      "email address": "email",
      "email": "email",
      "tenant phone": "phone",
      "phone number": "phone",
      "phone": "phone",
      "property": "propertyName",
      "property name": "propertyName",
      "building": "propertyName",
      "property address": "address",
      "address": "address",
      "city": "city",
      "state": "state",
      "zip": "zip",
      "zip code": "zip",
      "unit": "unitNumber",
      "unit number": "unitNumber",
      "unit #": "unitNumber",
      "apt": "unitNumber",
      "apt #": "unitNumber",
      "beds": "bedrooms",
      "bedrooms": "bedrooms",
      "baths": "bathrooms",
      "bathrooms": "bathrooms",
      "sq ft": "sqft",
      "square feet": "sqft",
      "rent": "rentAmount",
      "monthly rent": "rentAmount",
      "rent amount": "rentAmount",
      "lease start": "leaseStart",
      "lease start date": "leaseStart",
      "move in": "leaseStart",
      "move in date": "leaseStart",
      "lease end": "leaseEnd",
      "lease end date": "leaseEnd",
      "lease expiration": "leaseEnd",
      "move out": "leaseEnd",
    },
    supportedFields: [
      "name", "email", "phone", "propertyName", "address", "city",
      "state", "zip", "unitNumber", "bedrooms", "bathrooms", "sqft",
      "rentAmount", "leaseStart", "leaseEnd",
    ],
  },
  {
    id: "appfolio",
    name: "AppFolio",
    description: "Import from AppFolio tenant report export",
    instructions:
      "In AppFolio, go to Reports → Tenant Directory. Export the report as CSV and upload it here.",
    columnAliases: {
      "tenant": "name",
      "tenant name": "name",
      "name": "name",
      "email": "email",
      "primary email": "email",
      "phone": "phone",
      "primary phone": "phone",
      "cell phone": "phone",
      "property": "propertyName",
      "property name": "propertyName",
      "property address": "address",
      "street address": "address",
      "city": "city",
      "state": "state",
      "zip": "zip",
      "postal code": "zip",
      "unit": "unitNumber",
      "unit number": "unitNumber",
      "unit id": "unitNumber",
      "bedrooms": "bedrooms",
      "bed": "bedrooms",
      "bathrooms": "bathrooms",
      "bath": "bathrooms",
      "sqft": "sqft",
      "size": "sqft",
      "market rent": "rentAmount",
      "rent": "rentAmount",
      "monthly rent": "rentAmount",
      "current rent": "rentAmount",
      "lease from": "leaseStart",
      "lease start": "leaseStart",
      "move-in date": "leaseStart",
      "lease to": "leaseEnd",
      "lease end": "leaseEnd",
      "lease expiration": "leaseEnd",
    },
    supportedFields: [
      "name", "email", "phone", "propertyName", "address", "city",
      "state", "zip", "unitNumber", "bedrooms", "bathrooms", "sqft",
      "rentAmount", "leaseStart", "leaseEnd",
    ],
  },
  {
    id: "yardi",
    name: "Yardi",
    description: "Import from Yardi Voyager tenant data export",
    instructions:
      "In Yardi Voyager, go to Residents → Resident List. Export the data as CSV and upload it here.",
    columnAliases: {
      "resident name": "name",
      "tenant name": "name",
      "name": "name",
      "resident": "name",
      "email": "email",
      "email address": "email",
      "phone": "phone",
      "home phone": "phone",
      "mobile phone": "phone",
      "property code": "propertyName",
      "property name": "propertyName",
      "property": "propertyName",
      "address": "address",
      "property address": "address",
      "city": "city",
      "state": "state",
      "zip": "zip",
      "unit code": "unitNumber",
      "unit": "unitNumber",
      "space": "unitNumber",
      "bedrooms": "bedrooms",
      "br": "bedrooms",
      "bathrooms": "bathrooms",
      "ba": "bathrooms",
      "sqft": "sqft",
      "area": "sqft",
      "rent charge": "rentAmount",
      "market rent": "rentAmount",
      "rent": "rentAmount",
      "lease from": "leaseStart",
      "lease start": "leaseStart",
      "move in": "leaseStart",
      "lease to": "leaseEnd",
      "lease end": "leaseEnd",
      "lease expiry": "leaseEnd",
    },
    supportedFields: [
      "name", "email", "phone", "propertyName", "address", "city",
      "state", "zip", "unitNumber", "bedrooms", "bathrooms", "sqft",
      "rentAmount", "leaseStart", "leaseEnd",
    ],
  },
  {
    id: "rent_manager",
    name: "Rent Manager",
    description: "Import from Rent Manager tenant export",
    instructions:
      "In Rent Manager, go to Reports → Tenant List. Export as CSV and upload it here.",
    columnAliases: {
      "tenant name": "name",
      "name": "name",
      "full name": "name",
      "email": "email",
      "email 1": "email",
      "phone": "phone",
      "phone 1": "phone",
      "mobile": "phone",
      "property": "propertyName",
      "property name": "propertyName",
      "location": "propertyName",
      "address": "address",
      "property address": "address",
      "city": "city",
      "state": "state",
      "zip": "zip",
      "zipcode": "zip",
      "unit": "unitNumber",
      "unit number": "unitNumber",
      "unit #": "unitNumber",
      "space": "unitNumber",
      "bedrooms": "bedrooms",
      "bathrooms": "bathrooms",
      "sq ft": "sqft",
      "square footage": "sqft",
      "rent": "rentAmount",
      "rent amount": "rentAmount",
      "monthly charge": "rentAmount",
      "lease begin": "leaseStart",
      "lease start": "leaseStart",
      "start date": "leaseStart",
      "move-in": "leaseStart",
      "lease expire": "leaseEnd",
      "lease end": "leaseEnd",
      "end date": "leaseEnd",
    },
    supportedFields: [
      "name", "email", "phone", "propertyName", "address", "city",
      "state", "zip", "unitNumber", "bedrooms", "bathrooms", "sqft",
      "rentAmount", "leaseStart", "leaseEnd",
    ],
  },
  {
    id: "generic",
    name: "Generic CSV",
    description: "Import from any CSV with standard column names",
    instructions:
      "Upload a CSV file with your tenant data. Map the columns in the next step.",
    columnAliases: {
      "name": "name",
      "full name": "name",
      "tenant name": "name",
      "tenant": "name",
      "email": "email",
      "email address": "email",
      "phone": "phone",
      "phone number": "phone",
      "property": "propertyName",
      "property name": "propertyName",
      "address": "address",
      "city": "city",
      "state": "state",
      "zip": "zip",
      "zip code": "zip",
      "unit": "unitNumber",
      "unit number": "unitNumber",
      "unit #": "unitNumber",
      "apt": "unitNumber",
      "bedrooms": "bedrooms",
      "beds": "bedrooms",
      "bathrooms": "bathrooms",
      "baths": "bathrooms",
      "sqft": "sqft",
      "sq ft": "sqft",
      "rent": "rentAmount",
      "rent amount": "rentAmount",
      "monthly rent": "rentAmount",
      "lease start": "leaseStart",
      "start date": "leaseStart",
      "move in": "leaseStart",
      "lease end": "leaseEnd",
      "end date": "leaseEnd",
      "move out": "leaseEnd",
      "rent split %": "splitPercent",
    },
    supportedFields: [
      "name", "email", "phone", "propertyName", "address", "city",
      "state", "zip", "unitNumber", "bedrooms", "bathrooms", "sqft",
      "rentAmount", "leaseStart", "leaseEnd",
    ],
  },
];

/**
 * Auto-map source columns to DoorStax fields using platform preset aliases.
 * Returns a mapping of sourceColumn → doorstaxField.
 */
export function autoMapColumns(
  sourceColumns: string[],
  preset: PlatformPreset
): Record<string, string> {
  const mapping: Record<string, string> = {};

  for (const col of sourceColumns) {
    const normalized = col.toLowerCase().trim();
    // Check preset aliases first
    if (preset.columnAliases[normalized]) {
      mapping[col] = preset.columnAliases[normalized];
    }
  }

  return mapping;
}
