/**
 * Platform-specific column mapping presets for property/unit data migration.
 * Each preset maps the source platform's export column names to DoorStax field names.
 */

import type { PlatformPreset } from "@/lib/migration-presets";

export const PROPERTY_DOORSTAX_FIELDS = [
  { key: "propertyName", label: "Property Name", required: true },
  { key: "address", label: "Address", required: true },
  { key: "city", label: "City", required: false },
  { key: "state", label: "State", required: false },
  { key: "zip", label: "ZIP Code", required: false },
  { key: "propertyType", label: "Property Type", required: false },
  { key: "unitNumber", label: "Unit Number", required: true },
  { key: "bedrooms", label: "Bedrooms", required: false },
  { key: "bathrooms", label: "Bathrooms", required: false },
  { key: "sqft", label: "Sq Ft", required: false },
  { key: "rentAmount", label: "Rent Amount", required: true },
  { key: "dueDay", label: "Due Day", required: false },
  { key: "description", label: "Description", required: false },
] as const;

export const PROPERTY_MIGRATION_PRESETS: PlatformPreset[] = [
  {
    id: "buildium",
    name: "Buildium",
    description: "Import properties & units from Buildium CSV export",
    instructions:
      "In Buildium, go to Properties → All Properties → Export. Download the CSV file and upload it here.",
    columnAliases: {
      "property name": "propertyName",
      "property": "propertyName",
      "building": "propertyName",
      "building name": "propertyName",
      "name": "propertyName",
      "street address": "address",
      "address": "address",
      "property address": "address",
      "street": "address",
      "city": "city",
      "state": "state",
      "zip": "zip",
      "zip code": "zip",
      "postal code": "zip",
      "property type": "propertyType",
      "type": "propertyType",
      "unit": "unitNumber",
      "unit number": "unitNumber",
      "unit #": "unitNumber",
      "unit name": "unitNumber",
      "unit code": "unitNumber",
      "apt": "unitNumber",
      "apt #": "unitNumber",
      "number of bedrooms": "bedrooms",
      "bedrooms": "bedrooms",
      "beds": "bedrooms",
      "number of bathrooms": "bathrooms",
      "bathrooms": "bathrooms",
      "baths": "bathrooms",
      "square footage": "sqft",
      "sq ft": "sqft",
      "sqft": "sqft",
      "size": "sqft",
      "market rent": "rentAmount",
      "rent": "rentAmount",
      "rent amount": "rentAmount",
      "monthly rent": "rentAmount",
      "due day": "dueDay",
      "rent due day": "dueDay",
      "description": "description",
      "notes": "description",
    },
    supportedFields: [
      "propertyName", "address", "city", "state", "zip", "propertyType",
      "unitNumber", "bedrooms", "bathrooms", "sqft", "rentAmount",
      "dueDay", "description",
    ],
  },
  {
    id: "appfolio",
    name: "AppFolio",
    description: "Import properties & units from AppFolio report export",
    instructions:
      "In AppFolio, go to Reports → Property Directory. Export the report as CSV and upload it here.",
    columnAliases: {
      "property": "propertyName",
      "property name": "propertyName",
      "name": "propertyName",
      "street address": "address",
      "mailing address": "address",
      "address": "address",
      "property address": "address",
      "city": "city",
      "state": "state",
      "zip": "zip",
      "postal code": "zip",
      "property type": "propertyType",
      "type": "propertyType",
      "unit": "unitNumber",
      "unit number": "unitNumber",
      "unit id": "unitNumber",
      "unit name": "unitNumber",
      "bedrooms": "bedrooms",
      "bed": "bedrooms",
      "beds": "bedrooms",
      "bathrooms": "bathrooms",
      "bath": "bathrooms",
      "baths": "bathrooms",
      "sqft": "sqft",
      "size": "sqft",
      "sq ft": "sqft",
      "square feet": "sqft",
      "market rent": "rentAmount",
      "rent": "rentAmount",
      "monthly rent": "rentAmount",
      "current rent": "rentAmount",
      "rent amount": "rentAmount",
      "due day": "dueDay",
      "description": "description",
    },
    supportedFields: [
      "propertyName", "address", "city", "state", "zip", "propertyType",
      "unitNumber", "bedrooms", "bathrooms", "sqft", "rentAmount",
      "dueDay", "description",
    ],
  },
  {
    id: "yardi",
    name: "Yardi",
    description: "Import properties & units from Yardi Voyager data export",
    instructions:
      "In Yardi Voyager, go to Setup → Property Configuration → Export. Download the CSV and upload it here.",
    columnAliases: {
      "property code": "propertyName",
      "property name": "propertyName",
      "property": "propertyName",
      "name": "propertyName",
      "address": "address",
      "property address": "address",
      "street": "address",
      "city": "city",
      "state": "state",
      "zip": "zip",
      "postal code": "zip",
      "property type": "propertyType",
      "type": "propertyType",
      "unit code": "unitNumber",
      "unit": "unitNumber",
      "space": "unitNumber",
      "unit number": "unitNumber",
      "bedrooms": "bedrooms",
      "br": "bedrooms",
      "beds": "bedrooms",
      "bathrooms": "bathrooms",
      "ba": "bathrooms",
      "baths": "bathrooms",
      "sqft": "sqft",
      "area": "sqft",
      "sq ft": "sqft",
      "rent charge": "rentAmount",
      "market rent": "rentAmount",
      "rent": "rentAmount",
      "rent amount": "rentAmount",
      "due day": "dueDay",
      "description": "description",
      "notes": "description",
    },
    supportedFields: [
      "propertyName", "address", "city", "state", "zip", "propertyType",
      "unitNumber", "bedrooms", "bathrooms", "sqft", "rentAmount",
      "dueDay", "description",
    ],
  },
  {
    id: "rent_manager",
    name: "Rent Manager",
    description: "Import properties & units from Rent Manager export",
    instructions:
      "In Rent Manager, go to Reports → Property List. Export as CSV and upload it here.",
    columnAliases: {
      "property": "propertyName",
      "property name": "propertyName",
      "location": "propertyName",
      "location name": "propertyName",
      "name": "propertyName",
      "address": "address",
      "property address": "address",
      "street": "address",
      "city": "city",
      "state": "state",
      "zip": "zip",
      "zipcode": "zip",
      "zip code": "zip",
      "property type": "propertyType",
      "type": "propertyType",
      "unit": "unitNumber",
      "unit number": "unitNumber",
      "unit #": "unitNumber",
      "space": "unitNumber",
      "bedrooms": "bedrooms",
      "beds": "bedrooms",
      "bathrooms": "bathrooms",
      "baths": "bathrooms",
      "sq ft": "sqft",
      "square footage": "sqft",
      "sqft": "sqft",
      "rent": "rentAmount",
      "rent amount": "rentAmount",
      "monthly charge": "rentAmount",
      "market rent": "rentAmount",
      "due day": "dueDay",
      "rent due": "dueDay",
      "description": "description",
      "notes": "description",
    },
    supportedFields: [
      "propertyName", "address", "city", "state", "zip", "propertyType",
      "unitNumber", "bedrooms", "bathrooms", "sqft", "rentAmount",
      "dueDay", "description",
    ],
  },
  {
    id: "generic",
    name: "Generic CSV",
    description: "Import from any CSV with standard column names",
    instructions:
      "Upload a CSV file with your property data. Map the columns in the next step.",
    columnAliases: {
      "property name": "propertyName",
      "property": "propertyName",
      "name": "propertyName",
      "building": "propertyName",
      "address": "address",
      "street address": "address",
      "street": "address",
      "city": "city",
      "state": "state",
      "zip": "zip",
      "zip code": "zip",
      "postal code": "zip",
      "property type": "propertyType",
      "type": "propertyType",
      "unit": "unitNumber",
      "unit number": "unitNumber",
      "unit #": "unitNumber",
      "apt": "unitNumber",
      "apt #": "unitNumber",
      "bedrooms": "bedrooms",
      "beds": "bedrooms",
      "bathrooms": "bathrooms",
      "baths": "bathrooms",
      "sqft": "sqft",
      "sq ft": "sqft",
      "square feet": "sqft",
      "rent": "rentAmount",
      "rent amount": "rentAmount",
      "monthly rent": "rentAmount",
      "market rent": "rentAmount",
      "due day": "dueDay",
      "description": "description",
      "notes": "description",
    },
    supportedFields: [
      "propertyName", "address", "city", "state", "zip", "propertyType",
      "unitNumber", "bedrooms", "bathrooms", "sqft", "rentAmount",
      "dueDay", "description",
    ],
  },
];
