import { emailStyles, emailHeader, emailFooter, emailButton } from "./_layout";

const BASE_URL = process.env.NEXT_PUBLIC_APP_URL || "https://doorstax.com";

export function merchantStatementEmail(data: {
  pmName: string;
  statementDate: string;
  periodLabel: string;
}): string {
  const { pmName, statementDate, periodLabel } = data;

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    ${emailStyles(`
    .btn { padding: 14px 40px; font-size: 16px; }
    .btn-container { margin: 28px 0; }
    .note { font-size: 12px; color: #999; text-align: center; margin-top: 16px; }
    `)}
  </style>
</head>
<body>
  <div class="container">
    <div class="card">
      ${emailHeader()}
      <h1>Your Merchant Statement</h1>
      <p>Hi ${pmName},</p>
      <p>Your merchant processing statement for <strong>${periodLabel}</strong> is attached to this email.</p>
      <div class="highlight">
        <table>
          <tr><td>Statement Date</td><td>${statementDate}</td></tr>
          <tr><td>Period</td><td>${periodLabel}</td></tr>
        </table>
      </div>
      ${emailButton("View Reporting Dashboard", `${BASE_URL}/dashboard/statements`)}
      <p class="note">This statement is generated by Kadima Payments and reflects your merchant processing activity.</p>
    </div>
    ${emailFooter()}
  </div>
</body>
</html>`.trim();
}
