export const dynamic = "force-dynamic";

import Link from "next/link";
import { requireAdminPermission } from "@/lib/auth-utils";
import { db } from "@/lib/db";
import { PageHeader } from "@/components/ui/page-header";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/empty-state";
import { formatCurrency, formatDate } from "@/lib/utils";
import { FileText, ExternalLink } from "lucide-react";

export const metadata = { title: "Statements — Admin" };

export default async function AdminStatementsPage({
  searchParams,
}: {
  searchParams: Promise<{ period?: string }>;
}) {
  await requireAdminPermission("admin:expenses");

  const { period } = await searchParams;
  const now = new Date();
  const defaultPeriod =
    now.getFullYear() + "-" + String(now.getMonth() + 1).padStart(2, "0");
  const selectedPeriod = period || defaultPeriod;

  // Pull snapshots for the selected period
  const snapshots = await db.monthlySnapshot.findMany({
    where: { period: selectedPeriod },
    orderBy: { netRevenue: "desc" },
    include: {
      user: {
        select: {
          id: true,
          name: true,
          email: true,
          companyName: true,
          currentTier: true,
        },
      },
    },
  });

  // List of all distinct periods for the period picker
  const distinctPeriodsRaw = await db.monthlySnapshot.findMany({
    distinct: ["period"],
    select: { period: true },
    orderBy: { period: "desc" },
    take: 24,
  });
  const distinctPeriods = distinctPeriodsRaw.map((p) => p.period);

  // Totals for this period
  const totals = snapshots.reduce(
    (acc, s) => ({
      cardVolume: acc.cardVolume + s.cardVolume,
      cardRevenue: acc.cardRevenue + s.cardRevenue,
      achRevenue: acc.achRevenue + s.achRevenue,
      subscriptionAmount: acc.subscriptionAmount + s.subscriptionAmount,
      netRevenue: acc.netRevenue + s.netRevenue,
      pmPayout: acc.pmPayout + s.pmPayout,
    }),
    {
      cardVolume: 0,
      cardRevenue: 0,
      achRevenue: 0,
      subscriptionAmount: 0,
      netRevenue: 0,
      pmPayout: 0,
    }
  );

  return (
    <div className="space-y-6 page-enter">
      <PageHeader
        title="Statements"
        description="Monthly snapshot per property manager. Click a PM to see detailed statements and reports."
      />

      {/* Period picker */}
      <div className="flex items-center gap-3">
        <label className="text-xs uppercase tracking-wider text-muted-foreground">
          Period:
        </label>
        <div className="flex flex-wrap gap-1.5">
          {distinctPeriods.length === 0 && (
            <Badge variant="outline" className="text-xs">
              {selectedPeriod}
            </Badge>
          )}
          {distinctPeriods.map((p) => (
            <Link
              key={p}
              href={`/admin/statements?period=${p}`}
              className={
                "rounded-full px-2.5 py-1 text-xs font-medium border transition-colors " +
                (p === selectedPeriod
                  ? "bg-primary/10 text-primary border-primary/30"
                  : "hover:bg-muted border-border")
              }
            >
              {p}
            </Link>
          ))}
        </div>
      </div>

      {/* Totals */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 animate-stagger">
        <StatTile label="Card Volume" value={formatCurrency(totals.cardVolume)} />
        <StatTile
          label="Card + ACH Revenue"
          value={formatCurrency(totals.cardRevenue + totals.achRevenue)}
        />
        <StatTile
          label="Subscription MRR"
          value={formatCurrency(totals.subscriptionAmount)}
        />
        <StatTile
          label="Net Revenue"
          value={formatCurrency(totals.netRevenue)}
          highlight
        />
      </div>

      {/* Snapshot table */}
      {snapshots.length === 0 ? (
        <EmptyState
          icon={<FileText className="h-12 w-12" />}
          title={`No statements for ${selectedPeriod}`}
          description="MonthlySnapshot rows are generated by the monthly-snapshot cron on the 1st. Check back on the 1st of next month."
        />
      ) : (
        <Card className="border-border">
          <CardContent className="p-0">
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b text-xs text-muted-foreground uppercase tracking-wider">
                    <th className="text-left p-3">PM</th>
                    <th className="text-left p-3">Tier</th>
                    <th className="text-right p-3">Units</th>
                    <th className="text-right p-3">Card Vol</th>
                    <th className="text-right p-3">ACH #</th>
                    <th className="text-right p-3">Subscription</th>
                    <th className="text-right p-3">PM Payout</th>
                    <th className="text-right p-3">Net Rev</th>
                    <th className="text-left p-3">Generated</th>
                    <th className="text-center p-3"></th>
                  </tr>
                </thead>
                <tbody>
                  {snapshots.map((s) => (
                    <tr
                      key={s.id}
                      className="border-b last:border-0 hover:bg-muted/20"
                    >
                      <td className="p-3">
                        <div className="font-medium">
                          {s.user.companyName || s.user.name || "Unknown"}
                        </div>
                        <div className="text-xs text-muted-foreground">
                          {s.user.email}
                        </div>
                      </td>
                      <td className="p-3">{s.tierName}</td>
                      <td className="p-3 text-right">{s.unitCount}</td>
                      <td className="p-3 text-right">
                        {formatCurrency(s.cardVolume)}
                      </td>
                      <td className="p-3 text-right">{s.achTransactions}</td>
                      <td className="p-3 text-right">
                        {formatCurrency(s.subscriptionAmount)}
                      </td>
                      <td className="p-3 text-right text-amber-500">
                        {formatCurrency(s.pmPayout)}
                      </td>
                      <td className="p-3 text-right font-medium text-emerald-500">
                        {formatCurrency(s.netRevenue)}
                      </td>
                      <td className="p-3 text-xs text-muted-foreground">
                        {formatDate(s.createdAt)}
                      </td>
                      <td className="p-3 text-center">
                        <Link
                          href={`/admin/merchants`}
                          className="text-xs text-primary hover:underline inline-flex items-center gap-1"
                          title="View PM profile"
                        >
                          <ExternalLink className="h-3 w-3" />
                        </Link>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}

function StatTile({
  label,
  value,
  highlight = false,
}: {
  label: string;
  value: string;
  highlight?: boolean;
}) {
  return (
    <Card className={highlight ? "border-primary/30 card-hover" : "border-border card-hover"}>
      <CardContent className="p-4">
        <div className="text-xs text-muted-foreground uppercase tracking-wider">
          {label}
        </div>
        <div className={"text-2xl font-bold mt-1 " + (highlight ? "text-primary" : "")}>
          {value}
        </div>
      </CardContent>
    </Card>
  );
}
